// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvZvymal90GXmFpC-HjUT7nqbfJECyGM0',
    appId: '1:934994699192:web:cc9d3923d537633e0a654d',
    messagingSenderId: '934994699192',
    projectId: 'mynotes-paras-c02a0',
    authDomain: 'mynotes-paras-c02a0.firebaseapp.com',
    storageBucket: 'mynotes-paras-c02a0.firebasestorage.app',
    measurementId: 'G-FP7SBJ0ZX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP58uv9LPA6LpRKVDu6tsgfkuUHWHwscs',
    appId: '1:934994699192:android:8be5c3ccfc0d564a0a654d',
    messagingSenderId: '934994699192',
    projectId: 'mynotes-paras-c02a0',
    storageBucket: 'mynotes-paras-c02a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zMa_ET-6gCzF48Y1QQMY2Wk3YBIuvB4',
    appId: '1:934994699192:ios:33aef7f71ceed60c0a654d',
    messagingSenderId: '934994699192',
    projectId: 'mynotes-paras-c02a0',
    storageBucket: 'mynotes-paras-c02a0.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zMa_ET-6gCzF48Y1QQMY2Wk3YBIuvB4',
    appId: '1:934994699192:ios:33aef7f71ceed60c0a654d',
    messagingSenderId: '934994699192',
    projectId: 'mynotes-paras-c02a0',
    storageBucket: 'mynotes-paras-c02a0.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvZvymal90GXmFpC-HjUT7nqbfJECyGM0',
    appId: '1:934994699192:web:dce152898f2099170a654d',
    messagingSenderId: '934994699192',
    projectId: 'mynotes-paras-c02a0',
    authDomain: 'mynotes-paras-c02a0.firebaseapp.com',
    storageBucket: 'mynotes-paras-c02a0.firebasestorage.app',
    measurementId: 'G-GHL934DG5P',
  );
}
